---
kind: pipeline
type: docker
name: alpine

platform:
  os: linux
  arch: amd64

trigger:
  ref:
    - refs/heads/master
    - refs/pull/*/head
    - refs/tags/*

steps:
   
  - name: create image virt
    image: alpine:3.13
    commands:
      - apk add make squashfs-tools
      - mkdir dist
      - ls -lha ./     
      - make virt
    depends_on: ['clean pre build']
  
  - name: create image lts
    image: alpine:3.13
    commands:
      - apk add make squashfs-tools
      - make lts
    depends_on: ['clean pre build']

  - name: clean
    image: alpine:3.13
    commands:
      - apk add make
      - make clean
    depends_on: ['create image lts', 'create image virt']

  - name: publish
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files: dist/*
      checksum:
        - md5
        - sha1
    when:
      event: [tag]
    depends_on: ['clean']
  
  - name: notify
    image: appleboy/drone-telegram
    settings:
      token:
        from_secret: telegram_token
      to: 205514323
    when:
      status: [ success, failure ]
      event: [tag]
    depends_on: ['publish']
