---
kind: pipeline
type: docker
name: alpine

trigger:
  ref:
  - refs/heads/master
  - refs/pull/*/head

platform:
  os: linux
  arch: amd64

steps:
  - name: Build
    image: alpine:edge
    commands:
      - echo "Hello world"
      - exit 0
  - name: Notify
    image: appleboy/drone-telegram
    settings:
      token:
        from_secret: telegram_token
      to: 205514323
    when:
      status: [ success, failure ]
    depends_on: ['Build']
