---
kind: pipeline
type: docker
name: alpine

platform:
  os: linux
  arch: amd64

trigger:
  ref:
    - refs/heads/master
    - refs/pull/*/head
    - refs/tags/*

volumes:
- name: cache
  temp: {}

steps:
  - name: create image virt
    image: alpine
    volumes:
      - name: cache
        path: /build
    commands:
      - apk add make squashfs-tools
      - cp init /build
      - cp Makefile /build
      - cd /build && make virt
  
  - name: create image lts
    image: alpine
    volumes:
      - name: cache
        path: /build
    commands:
      - apk add make squashfs-tools
      - cp init /build
      - cp Makefile /build
      - cd /build && make lts

  - name: clean
    image: alpine
    volumes:
      - name: cache
        path: /build
    commands:
      - apk add make
      - cp Makefile /build
      - cd /build && make clean
    depends_on: ['create image lts', 'create image virt']

  - name: publish
    image: plugins/github-release
    volumes:
      - name: cache
        path: /build
    settings:
      api_key:
        from_secret: github_token
      files: /build/dist/*
      checksum:
        - md5
        - sha1
    when:
      event: [tag]
    depends_on: ['clean']
  
  - name: notify
    image: appleboy/drone-telegram
    settings:
      token:
        from_secret: telegram_token
      to: 205514323
    when:
      status: [ success, failure ]
      event: [tag]
    depends_on: ['publish']
