---
kind: pipeline
type: docker
name: alpine

platform:
  os: linux
  arch: amd64

steps:
  - name: Notify
    image: appleboy/drone-telegram
    settings:
      token:
        from_secret: telegram_token
      to: 205514323
