---
kind: pipeline
type: docker
name: alpine

trigger:
  ref:
    - refs/heads/master
    - refs/pull/*/head
    - refs/tags/*

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: alpine:edge
    commands:
      - mkdir dist
      - date > dist/echo.txt
      - echo "Hello world" >> dist/echo.txt
      - pwd

  - name: publish
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
    files: dist/*
    checksum:
      - md5
      - sha1
    when:
      event: [tag]
    depends_on: ['build']
  
  - name: notify
    image: appleboy/drone-telegram
    settings:
      token:
        from_secret: telegram_token
      to: 205514323
    when:
      status: [ success, failure ]
      event: [tag]
    depends_on: ['publish']
