---
kind: pipeline
type: docker
name: alpine

platform:
  os: linux
  arch: amd64

steps:
  - name: Build
    image: alpine:edge
    commands:
      - echo "Hello world"
    when:
      ref:
      - refs/heads/master
      - refs/pull/*/head
  - name: Notify
    image: appleboy/drone-telegram
    settings:
      token:
        from_secret: telegram_token
      to: 205514323
    when:
      status: [ success, failure ]
    depends_on: ['Build']
